name: Crew Bidding System CI/CD

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run tests
        run: mvn clean test

      - name: Check Java version
        run: java --version

  #Building Docker image
  build-docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3

      - name: Build JAR for Docker
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t my-spring-app:latest .

      - name: Log in to Docker Hub
        if: always()
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: always()
        run: |
            docker tag my-spring-app:latest pgromiec/my-bidding-app:latest
            docker push pgromiec/my-bidding-app:latest